inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false

# Use plugins section for these extensions
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

# RSpec configurations
RSpec/MultipleExpectations:
  Enabled: true
  Max: 10
  Include:
    - 'spec/**/*_spec.rb'

# Explicitly define Capybara cops under RSpec namespace
Capybara:
  Enabled: true

# Explicitly define FactoryBot cops under RSpec namespace
FactoryBot:
  Enabled: true
